# Configuration pour déployer un site Docusaurus sur GitLab Pages
image: node:latest

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv build public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
