// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  presentationSidebar: [
    {
      type: 'link',
      label: 'Présentation',
      href: '/presentation',
    },
  ],

    // Sidebar pour la communauté
  comuSidebar: [
    {
      type: 'link',
      label: 'Communauté',
      href: '/communaute',
    },
  ],

  // Sidebar pour le blog "NumaWork"
  workSidebar: [
    {
      type: 'link',
      label: '@NumaWork',
      href: 'blog',
    },
  ],

  // Sidebar pour la présentation du logiciel
  introSidebar: [
    {
      type: 'category',
      label: 'Présentation du logiciel',
      items: [{ type: 'autogenerated', dirName: 'introduction' }],
    },
  ],

  // Sidebar pour le manuel administrateur
  adminSidebar: [
    {
      type: 'category',
      label: 'Accès administrateur',
      items: [{ type: 'autogenerated', dirName: 'administrateur' }],
    },
  ],

  // Sidebar pour le manuel utilisateur
  userSidebar: [
    {
      type: 'category',
      label: 'Accès utilisateur',
      items: [{ type: 'autogenerated', dirName: 'utilisateur' }],
    },
  ],

  // Sidebar pour le manuel prestataire
  prestaSidebar: [
    {
      type: 'category',
      label: 'Accès prestataire',
      items: [{ type: 'autogenerated', dirName: 'prestataire' }],
    },
  ],

  // Sidebar pour le glossaire
  glossaireSidebar: [
    {
      type: 'category',
      label: 'Glossaire',
      items: [{ type: 'autogenerated', dirName: 'glossaire' }],
    },
  ],
};

module.exports = sidebars;
