// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar principale pour la documentation
  docs: [
    {
      type: 'category',
      label: 'Présentation du logiciel',
      link: {
        type: 'generated-index',
        title: 'Présentation du logiciel',
        slug: '/introduction',
      },
      items: [{ type: 'autogenerated', dirName: 'introduction' }],
    },
    {
      type: 'category',
      label: 'Accès administrateur',
      link: {
        type: 'generated-index',
        title: 'Accès administrateurs',
        slug: '/administrateur',
      },
      items: [{ type: 'autogenerated', dirName: 'administrateur' }],
    },
    {
      type: 'category',
      label: 'Accès utilisateur',
      link: {
        type: 'generated-index',
        title: 'Accès utilisateurs',
        slug: '/utilisateur',
      },
      items: [{ type: 'autogenerated', dirName: 'utilisateur' }],
    },
    {
      type: 'category',
      label: 'Accès prestataire',
      link: {
        type: 'generated-index',
        title: 'Accès prestataires',
        slug: '/prestataire',
      },
      items: [{ type: 'autogenerated', dirName: 'prestataire' }],
    },
    {
      type: 'category',
      label: 'Glossaire',
      items: [{ type: 'autogenerated', dirName: 'glossaire' }],
    },
    {
      type: 'category',
      label: 'Cas pratiques',
      link: {
        type: 'generated-index',
        title: 'Cas pratiques',
        slug: '/pratiques',
      },
      items: [{ type: 'autogenerated', dirName: 'pratiques' }],
    },
  ],

  // Autres sidebars (pour les autres sections du site)
  presentationSidebar: [
    {
      type: 'link',
      label: 'Présentation',
      href: '/presentation',
    },
  ],
  comuSidebar: [
    {
      type: 'link',
      label: 'Communauté',
      href: '/communaute',
    },
  ],
  workSidebar: [
    {
      type: 'link',
      label: '@NumaWork',
      href: 'blog',
    },
  ],
};

module.exports = sidebars;