// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  presentationSidebar: [
    {
      type: 'link',
      label: 'Présentation',
      href: '/presentation',
    },
  ],

  // Sidebar pour la communauté
  comuSidebar: [
    {
      type: 'link',
      label: 'Communauté',
      href: '/communaute',
    },
  ],

  // Sidebar pour le blog "NumaWork"
  workSidebar: [
    {
      type: 'link',
      label: '@NumaWork',
      href: 'blog',
    },
  ],

  // Sidebar pour la présentation du logiciel
  introSidebar: [
    {
      type: 'category',
      label: 'Présentation du logiciel',
      link: {
        type: 'generated-index',  // Utilise 'generated-index' pour une page d'index automatique
        title: 'Présentation du logiciel',
        slug: '/introduction',  // Doit correspondre au chemin du dossier
      },
      items: [{ type: 'autogenerated', dirName: 'introduction' }],
    },
  ],


  // Sidebar pour le manuel administrateur
  adminSidebar: [
    {
      type: 'category',
      label: 'Accès administrateur',
      link: {
        type: 'generated-index',  // Utilise 'generated-index' pour une page d'index automatique
        title: 'Accès administrateurs',
        slug: '/administrateur',
      },
      items: [{ type: 'autogenerated', dirName: 'administrateur' }],
    },
  ],

  // Sidebar pour le manuel utilisateur
  userSidebar: [
    {
      type: 'category',
      label: 'Accès utilisateur',
      link: {
        type: 'generated-index',  // Utilise 'generated-index' pour une page d'index automatique
        title: 'Accès utilisateurs',
        slug: '/utilisateur',
      },
      items: [{ type: 'autogenerated', dirName: 'utilisateur' }],
    },
  ],

  // Sidebar pour le manuel prestataire
  prestaSidebar: [
    {
      type: 'category',
      label: 'Accès prestataire',
      link: {
        type: 'generated-index',
        title: 'Accès prestataires',
        slug: '/prestataire',
      },
      items: [{ type: 'autogenerated', dirName: 'prestataire' }],
    },
  ],

  // Sidebar pour le glossaire
  glossaireSidebar: [
    {
      type: 'category',
      label: 'Glossaire',
      items: [{ type: 'autogenerated', dirName: 'glossaire' }],
    },
  ],

  // Sidebar pour les cas pratiques
  pratiquesSidebar: [
    {
      type: 'category',
      label: 'Cas pratiques',
      link: {
        type: 'generated-index',
        title: 'Accès prestataires',
        slug: '/pratiques',
      },
      items: [{ type: 'autogenerated', dirName: 'pratiques' }],
    },
  ],
};

module.exports = sidebars;
